"""Write Blueprints/DSH_Enemies/Generate.cs from the validated Python model.

The C# file is the artefact that actually runs in the Editor; the Python model is the
source of truth for what it emits.  Generating the former from the latter keeps the two in
lockstep, so a change to a hull cannot silently diverge from what gets written to disk.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import design_model as M

HEADER = '''// DSH enemy blueprint generator.
//
//   unity command eval_file --file Blueprints/DSH_Enemies/Generate.cs --json
//
// Emits three enemy blueprints (DSH_E01_Skimmer, DSH_E02_Halberd, DSH_E03_Talos) into the
// repository copy under Blueprints/DSH_Enemies and into the live
// Application.persistentDataPath/EnemyBlueprints the game reads, then reports mass, lift,
// thrust and power for each.
//
// THIS FILE IS GENERATED by Blueprints/DSH_Enemies/write_generator.py from the validated
// layout model in Blueprints/DSH_Enemies/design_model.py.  Edit the model and re-run that
// script rather than hand-editing the block list below.
//
// Only stock parts and stock numbers are used; no prefab, AI or flight-controller value is
// modified.  The layouts were derived from the shipped CODEX enemies' real connector
// geometry and re-checked by Blueprints/DSH_Enemies/Validate.cs:
//   * a 2x2x2 part spans [c-1, c+1], so deck and pod centres sit on even coordinates and
//     1x1x1 parts sit on half-integer centres;
//   * a HoverThrusterBig at y = -2 has its Up sockets at y = -1, exactly where the deck
//     block above it has its Down sockets, so the ring hangs directly under the deck;
//   * cockpit and generators sit one rung up at (x, 2, z), where their Down sockets meet
//     that deck block's Up sockets (at the same centre they would miss by 1 m);
//   * 1x1x1 equipment hangs under the deck rolled 180 degrees about X, so its Down socket
//     points up into the deck block's Down socket; the deck's top face is unusable because
//     the station blocks occupy y in [1, 3];
//   * omni thrusters are mounted the same way, which works because UniversalThruster
//     re-aims its model in world space every FixedUpdate and so needs no authored facing.
string folder = System.IO.Path.GetFullPath("Blueprints/DSH_Enemies");
string destination = System.IO.Path.Combine(UnityEngine.Application.persistentDataPath, "EnemyBlueprints");
System.IO.Directory.CreateDirectory(folder);
System.IO.Directory.CreateDirectory(destination);

UnityEngine.Quaternion identity = UnityEngine.Quaternion.identity;
UnityEngine.Quaternion roll180x = UnityEngine.Quaternion.Euler(180f, 0f, 0f);
UnityEngine.Quaternion rollNeg90z = UnityEngine.Quaternion.Euler(0f, 0f, -90f);
UnityEngine.Quaternion rollPos90z = UnityEngine.Quaternion.Euler(0f, 0f, 90f);
UnityEngine.Quaternion roll180z = UnityEngine.Quaternion.Euler(0f, 0f, 180f);
var reports = new System.Collections.Generic.List<object>();

// One blueprint's worth of blocks.  Positions and rotations are the validated layout; the
// generator only re-checks them against the real prefabs before writing.
System.Action<string, string, System.Action<BlockDataList>> emit = (name, note, build) =>
{
    var data = new BlockDataList();
    build(data);
    if (data.blocks.Count == 0) throw new System.Exception(name + " is empty");
    reports.Add(Write(data, name, note, folder, destination));
};

System.Action<BlockDataList, string, float, float, float, UnityEngine.Quaternion> add =
    (data, type, x, y, z, rot) =>
{
    var prefab = UnityEngine.Resources.Load<UnityEngine.GameObject>("Blocks/" + type);
    if (prefab == null) throw new System.Exception("missing prefab Blocks/" + type);
    var block = prefab.GetComponent<Block>();
    if (block == null) throw new System.Exception("no Block component on " + type);
    if ((block.x == 2 && System.Math.Abs(x % 2) > 0.001f)
        || (block.z == 2 && System.Math.Abs(z % 2) > 0.001f))
    {
        throw new System.Exception(System.String.Format(
            "{0} at ({1},{2},{3}) breaks the 2 m lattice parity", type, x, y, z));
    }
    var d = UnityEngine.JsonUtility.FromJson<BlockData>("{}");
    d.id = data.blocks.Count.ToString("D3") + "_" + type;
    d.x = block.x; d.y = block.y; d.z = block.z;
    d.posX = x; d.posY = y; d.posZ = z;
    d.rotX = rot.x; d.rotY = rot.y; d.rotZ = rot.z; d.rotW = rot.w;
    d.resourcePath = "Assets/Resources/Blocks/" + type + ".prefab";
    d.cargo = new System.Collections.Generic.List<CargoItem>();
    data.blocks.Add(d);
};
'''

FOOTER = '''
// ---------------------------------------------------------------------------------------
object Write(BlockDataList data, string name, string note, string repoFolder, string liveFolder)
{
    float mass = 0f, lift = 0f, demand = 0f, supply = 0f, horizontal = 0f;
    var moment = UnityEngine.Vector3.zero;
    int cockpits = 0;
    foreach (var d in data.blocks)
    {
        var prefab = UnityEngine.Resources.Load<UnityEngine.GameObject>(
            BuildManager.ConvertToResourcesPath(d.resourcePath));
        if (prefab == null) throw new System.Exception("missing " + d.resourcePath);
        var block = prefab.GetComponent<Block>();
        mass += block.mass;
        moment += block.mass * new UnityEngine.Vector3(d.posX, d.posY, d.posZ);
        var power = prefab.GetComponent<Power>();
        if (power != null) demand += power.standardWorkingPower;
        var generator = prefab.GetComponent<PowerGeneratingUnit>();
        if (generator != null) supply += generator.outputPower;
        var hover = prefab.GetComponent<HoverThruster>();
        if (hover != null) lift += hover.maxThrust;
        var vector = prefab.GetComponent<UniversalThruster>();
        if (vector != null) horizontal += vector.maxThrust;
        if (prefab.GetComponent<Cockpit>() != null) cockpits++;
    }
    if (cockpits != 1) throw new System.Exception(name + " has " + cockpits + " cockpits");

    string json = UnityEngine.JsonUtility.ToJson(data, true);
    foreach (string target in new[] { repoFolder, liveFolder })
    {
        string path = System.IO.Path.Combine(target, name + ".json");
        if (System.IO.File.Exists(path) && System.IO.File.ReadAllText(path) != json)
            throw new System.Exception("refusing to overwrite a different file: " + path);
        System.IO.File.WriteAllText(path, json, new System.Text.UTF8Encoding(false));
    }
    return new
    {
        name,
        note,
        blocks = data.blocks.Count,
        mass,
        centerOfMass = (moment / mass).ToString("F3"),
        lift,
        liftWeightRatio = lift / (mass * 9.81f),
        horizontalThrust = horizontal,
        powerDemand = demand,
        powerSupply = supply,
    };
}

return new { destination, reports };
'''

NOTES = {
    "DSH_E01_Skimmer": "wide light interceptor",
    "DSH_E02_Halberd": "heavy long catamaran gunship",
    "DSH_E03_Talos": "disc gunship",
}


def rot_name(rot):
    """Name the handful of quaternions the model actually uses, as C# expressions."""
    for name, angle in (("roll180x", (180, "x")), ("rollNeg90z", (-90, "z")),
                        ("rollPos90z", (90, "z")), ("roll180z", (180, "z"))):
        if all(abs(rot[k] - M._q(angle[0], angle[1])[k]) < 1e-9 for k in range(4)):
            return name
    if all(abs(rot[k] - M.IDENTITY[k]) < 1e-9 for k in range(4)):
        return "identity"
    raise ValueError("unexpected rotation %r" % (rot,))


def fmt(v):
    """Format a coordinate as a C# float literal, e.g. -0.5f or 4f."""
    text = ("%g" % v)
    if text.endswith("."):
        text = text[:-1]
    return text + "f"


parts = [HEADER]
for builder in (M.build_e01, M.build_e02, M.build_e03):
    d = builder()
    r = d.report()
    parts.append('\n// %s - %s: %d blocks, mass %.0f, lift/weight %.2f, horizontal %d N.\n'
                 'emit("%s", "%s", data =>\n{\n'
                 % (d.name, NOTES[d.name], r["blocks"], r["mass"], r["lift_ratio"],
                    r["horizontal_thrust"], d.name, NOTES[d.name]))
    by_type = {}
    for b in d.blocks:
        by_type.setdefault(b["type"], []).append(b)
    for type_name in sorted(by_type):
        parts.append("    // %s x%d\n" % (type_name, len(by_type[type_name])))
        for b in sorted(by_type[type_name], key=lambda x: x["pos"]):
            p = b["pos"]
            parts.append('    add(data, "%s", %s, %s, %s, %s);\n'
                         % (type_name, fmt(p[0]), fmt(p[1]), fmt(p[2]), rot_name(b["rot"])))
    parts.append("});\n")

parts.append(FOOTER)

path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Generate.cs")
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write("".join(parts))
print("wrote", path, len("".join(parts)), "bytes")
